version: '3.8'

services:
  dirtgenie-web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      # Mount local trips directory for persistent storage
      - ./trips:/app/trips
      # Mount profile.yml if it exists
      - ./profile.yml:/app/profile.yml:ro
    command: ["web"]
    restart: unless-stopped

  dirtgenie-cli:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      # Mount current directory for CLI output
      - .:/data
    working_dir: /data
    profiles: ["cli"]
    command: ["cli", "--help"]

networks:
  default:
    name: dirtgenie
